stages:
  - build
  - run

default:
  image: openjdk:11-jdk-slim
  tags: ["kubernetes"]

build:
  stage: build
  script:
  - echo "Building docker image..."
  - docker build . -t ghidra_plugin

run:
  stage: run
  script:
  - echo "Running docker image..."
  - docker run -ti ghidra_plugin
