stages:
  - build

default:
  image: $DOCKER_REGISTRY/$CI_PROJECT_NAMESPACE/gtirb-ghidra-plugin
  tags: ["kubernetes"]

build:
  stage: build
  script:
  - echo "Building docker image..."
  - /workspace/build-plugin