stages:
  - build

default:
  image: docker.grammatech.com/rewriting/gtirb-ghidra-plugin
  tags: ["kubernetes"]

build:
  stage: build
  script:
  - echo "Building docker image..."
  - /workspace/build-plugin